server:
  port: 8082

spring:
  application:
    name: colin-provider
  cloud:
    nacos:
      discovery:
        server-addr: 47.100.54.86:8488
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8888
      # 该配置能够使 dashboard 主动发现该应用
      eager: true